---
# tasks/install_packages.yml
- name: Install common packages
  become: true
  # package:   # conflicting action statements: package, debug
  #   name: "{{ item }}"
  #   state: present
  loop:
    - htop
    - curl
    - wget
  debug:
    msg: "Installing {{ item }}"
  # A debug task does not have a changed state. A change is required for an handler to trigger
  changed_when: true
  notify: Run post-install handler

